sudo: required
dist: trusty

addons:
  chrome: stable
  # apt:
  #   sources:
  #     - google-chrome
  #   packages:
  #     - google-chrome-stable

language: node_js
node_js:
  - '6.11'

# Should skip the install phase
# install: true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
#  - npm install -g webdriver-manager
#  - webdriver-manager update
#  - webdriver-manager start &
#  - sleep 3
#  - netstat -plant
  
  # - ./node_modules/protractor/bin/install_selenium_standalone
  # - nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &"
  # - sleep 5
#   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#   - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#   - sudo apt-get update -q
#   - sudo apt-get install -q google-chrome-stable

install:
  # - npm install -g selenium-webdriver
  - npm install
  - export PATH=$PWD/node_modules/protractor/node_modules/webdriver-manager/bin:$PATH
  - webdriver-manager update

script:
  - echo "Triggered through push!"
  - SELENIUM_VERSION=$(webdriver-manager status | grep standalone | awk '{print $(NF-1)}')
  - export SELENIUM_SERVER_JAR=$PWD/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-${SELENIUM_VERSION}.jar
  - pwd
  - env
  - gulp protractor-test

# after_success:
  # - TRAVIS_MAIN_FOLDER=./travis
  # - TRAVIS_FTP_SCRIPT=$TRAVIS_MAIN_FOLDER/ftp-deployer.sh
  # - chmod ugo+x $TRAVIS_FTP_SCRIPT
  # - $TRAVIS_FTP_SCRIPT


# after_failure
# before_deploy
# deploy
# after_deploy
# after_script
# 
# Deploy phase avoiding to change all the things done during the script intall phases
# deploy:
#   skip_cleanup: true
