sudo: required
dist: trusty

language: node_js
node_js:
  - '6.11'

# Should skip the install phase
# install: true

# install:
#   - export DISPLAY=:99.0
#   - sh -e /etc/init.d/xvfb start
#   - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#   - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
#   - sudo apt-get update -q
#   - sudo apt-get install -q google-chrome-stable

before_script:
  - npm install

script:
  - echo "Triggered through push!"
  # - gulp build

# after_success:
  # - TRAVIS_MAIN_FOLDER=./travis
  # - TRAVIS_FTP_SCRIPT=$TRAVIS_MAIN_FOLDER/ftp-deployer.sh
  # - chmod ugo+x $TRAVIS_FTP_SCRIPT
  # - $TRAVIS_FTP_SCRIPT


# after_failure
# before_deploy
# deploy
# after_deploy
# after_script
# 
# Deploy phase avoiding to change all the things done during the script intall phases
# deploy:
#   skip_cleanup: true